name: Workflow manual
on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: 'Mensaje a imprimir'
        required: true
        default: 'Hola mundo!'
jobs:
  mensaje-impreso:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje del usuario
        run: echo "Mensaje del usuario: ${{ github.event.inputs.mensaje }}"

